kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "fullname" . }}
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        release: "{{ .Release.Name }}"
        heritage: "{{ .Release.Service }}"
    spec:
      volumes:
        - name: api-config
          configMap:
            name: {{ .Release.Name }}-config
      containers:
      - name: {{ .Values.api.name }}
        image: {{ .Values.api.image.registry }}/{{ .Values.api.image.org }}/{{ .Values.api.image.name }}:{{ .Values.api.image.tag }}
        imagePullPolicy: {{ .Values.api.image.pullPolicy }}
        env:
        - name: PORT
          value: {{ .Values.api.port | quote }}
        - name: TILLER_HOST
          value: {{ .Values.api.tiller.host }}
        command: 
        - "./helm-ui"
        ports:
        - containerPort: {{ .Values.api.port }}
      - name: {{ .Values.frontend.name }}
        image: {{ .Values.frontend.image.registry }}/{{ .Values.frontend.image.org }}/{{ .Values.frontend.image.name }}:{{ .Values.frontend.image.tag }}
        imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
        command:
        - "caddy"
        - "-conf"
        - "/etc/Caddyfile"
        ports:
        - containerPort: {{ .Values.frontend.port }}
        volumeMounts:
        - name: api-config
          mountPath: /usr/src/app/src/app/config